### ISSUE TITLE
目录显示有问题

### ISSUE THREAD

**Issue by fpd3210** [iMaple/hugo-theme-icarus#1]
标题只会显示2 3 4级标题，如下图所示
![image](https://user-images.githubusercontent.com/43874190/99647050-381aca80-2a8c-11eb-810b-80d25f360f9f.png)

**Comment by iMaple** [comment]
在配置文件中定位相关配置项：
```
markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
```
将 `startLevel` 与 `endLevel` 设置为你想要的标题级别，范围为 1-6。
另，将 `startLevel` 设置为 1 后，目录显示可能会有问题，此问题待修复。
> https://gohugo.io/getting-started/configuration-markup/#table-of-contents
